[package]
name = "stacks-reference"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blockstack-core = { git = "https://github.com/stacks-network/stacks-blockchain" }
hex = "0.4.3"
